services:
  db:
    container_name: postgres_db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    networks:
      - reminder_network
    volumes:
      - reminder_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "6632:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
        - reminder_network
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy


volumes:
  reminder_db_data:
    driver: local

networks:
  reminder_network:
    driver: bridge
