spring:
  application:
    name: reminder
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/docker}
    username: ${JDBC_USERNAME:username}
    password: ${JDBC_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  mail:
    host: ${MAIL_HOST:smtp.mail.ru}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:example@mail.ru}
    password: ${MAIL_PASSWORD:1234 5678 9012 3456}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

token:
  signing:
    key: ${JWT_KEY:12A12E5F1C1E1A2D1B1F2D784E1A1B221D6F212D1F2E2C1A112D215A12122212}
